---
repos:
  - repo: https://github.com/UCL-MIRSG/.github
    rev: v0.239.0
    hooks:
      - id: mirsg-hooks
        exclude: ^.github/schemas/github-issue-forms.json$
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.19.1
    hooks:
      - id: mypy
        additional_dependencies:
          - types-requests
