[build-system]
build-backend = "setuptools.build_meta"
requires = [
    "setuptools",
    "setuptools-scm",
]

[dependency-groups]
build = [
    "build",
]
dev = [
    "nox",
    "nox-uv",
    {include-group = "build"},
    {include-group = "lint"},
]
docs = [
    "mkdocstrings",
    "mkdocstrings-python",
    "zensical",
]
lint = [
    "prek",
]
test = [
    "pytest",
    "pytest-cov",
    "xnat4tests",
]

[project]
authors = [
    {email = "arc.medical-imaging@ucl.ac.uk", name = "MIRSG Authors"},
]
classifiers = [
    "Operating System :: POSIX",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3 :: Only",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Programming Language :: Python :: 3.14",
    "Typing :: Typed",
]
dependencies = [
    "attrs",
    "cyclopts",
    "docker",
    "duckdb",
    "pandas",
    "pydantic-settings",
    "tqdm",
    "xnat",
]
description = "A Python package to migrate projects from one XNAT to another"
dynamic = [
    "version",
]
keywords = [
]
license = "MIT"
license-files = [
    "LICENSE.md",
]
name = "xmigrate"
readme = "README.md"
requires-python = ">=3.12"
scripts = {xmigrate = """xmigrate.cli:app"""}
urls.homepage = "https://github.com/UCL-MIRSG/xmigrate"

[tool.coverage]
report = {sort = "cover"}
run = {branch = true, parallel = true, source = [
    "xmigrate",
]}
paths.source = [
    "src",
    ".nox*/*/lib/python*/site-packages",
]

[tool.mypy]
explicit_package_bases = true
python_version = "3.12"

[tool.pytest.ini_options]
addopts = [
    "--color=yes",
    "--import-mode=importlib",
    "--verbose",
]
filterwarnings = [
    "ignore:Changing XNAT port from:UserWarning",
]
testpaths = [
    "tests/unit",
]

[tool.ruff]
fix = true
force-exclude = true
line-length = 120
lint.ignore = [
    "COM812", # trailing commas (ruff-format recommended)
    "D203", # no-blank-line-before-class
    "D212", # multi-line-summary-first-line
    "D407", # removed dashes lines under sections
    "D417", # argument description in docstring (unreliable)
    "ISC001", # simplify implicit str concatenation (ruff-format recommended)
]
lint.isort = {known-first-party = [
    "tests",
    "xmigrate",
], section-order = [
    "future",
    "standard-library",
    "third-party",
    "xnat",
    "first-party",
    "local-folder",
], sections = {"xnat" = [
    "medimages4tests",
    "xnat",
    "xnat4tests",
]}}
lint.per-file-ignores = {"tests/*" = [
    "INP001", # implicit-namespace-package
], "tests/fixtures/*" = [
    "INP001", # implicit-namespace-package
], "tests/integration/*" = [
    "INP001", # implicit-namespace-package
    "S101", # Checks for uses of the assert keyword
], "tests/unit/*" = [
    "INP001", # implicit-namespace-package
    "S101", # Checks for uses of the assert keyword
]}
lint.select = [
    "ALL",
]
lint.mccabe.max-complexity = 18
lint.pep8-naming.classmethod-decorators = [
    "classmethod",
]

[tool.setuptools]
include-package-data = true

[tool.setuptools.package-data]
xmigrate = [
    "sql/**/*.sql",
    "sql/*.sql",
]

[tool.setuptools_scm]
local_scheme = "no-local-version"
write_to = "src/xmigrate/_version.py"

[tool.tomlsort]
all = true
spaces_indent_inline_array = 4
trailing_comma_inline_array = true
overrides."project.classifiers".inline_arrays = false
overrides."tool.coverage.paths.source".inline_arrays = false
overrides."tool.ruff.lint.isort.section-order".inline_arrays = false
