---
name: Tests

on:
  push:
    branches:
      - main
  pull_request:
    types:
      - opened
      - ready_for_review
      - reopened
      - synchronize

concurrency:
  cancel-in-progress: true
  group: >-
    ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}

jobs:
  tests:
    if: github.event.pull_request.draft == false
    name: Run Tests (Python ${{ matrix.python-version }})
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version:
          - "3.12"
          - "3.13"
          - "3.14"
    steps:
      - name: Checkout source
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4

      - name: Set up uv
        uses: astral-sh/setup-uv@6ee6290f1cbc4156c0bdd66691b2c144ef8df19a # v7
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install only dev dependencies
        run: uv sync --only-dev

      - name: Test with nox
        run: uv run nox -s coverage-${{ matrix.python-version }} -- -s
        env:
          FORCE_COLOR: 1

      - name: Upload core coverage to Coveralls
        uses: coverallsapp/github-action@5cbfd81b66ca5d10c19b062c04de0199c215fb6e # v2
        with:
          flag-name: coverage-${{ matrix.python-version }}
          parallel: true

  aggregate-tests:
    needs:
      - tests
    if: always()
    runs-on: ubuntu-latest
    steps:
      - name: Coveralls finished
        uses: coverallsapp/github-action@5cbfd81b66ca5d10c19b062c04de0199c215fb6e # v2
        with:
          carryforward: coverage-3.12,coverage-3.13,coverage-3.14
          parallel-finished: true
