---
name: Tests

on:
  push:
    branches:
      - main
  pull_request:
    paths-ignore:
      - "**.md"

jobs:
  tests:
    name: Run Tests (Python ${{ matrix.python-version }})
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version:
          - "3.12"
          - "3.13"
          - "3.14"
    steps:
      - name: Checkout source
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4

      - name: Set up uv
        uses: astral-sh/setup-uv@6ee6290f1cbc4156c0bdd66691b2c144ef8df19a # v7
        with:
          python-version: ${{ matrix.python-version }}

      - name: Cache nox
        uses: actions/cache@5a3ec84eff668545956fd18022155c47e93e2684 # v4
        with:
          key:
            tests-${{ hashFiles('pyproject.toml') }}-${{ hashFiles('noxfile.py')
            }}-${{ matrix.python-version }}
          path: .nox

      - name: Install only dev dependencies
        run: uv sync --only-dev

      - name: Test with nox
        run: uv run nox -s tests-${{ matrix.python-version }}
